spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.mongodb.uri=mongodb+srv://apimongodb:minhaAPI2026@cluster0.rs8peom.mongodb.net/projeto_biblioteca?retryWrites=true&w=majority
spring.data.mongodb.database=projeto_biblioteca

spring.neo4j.uri=neo4j+s://d3dc5e09.databases.neo4j.io
spring.neo4j.authentication.username=d3dc5e09
spring.neo4j.authentication.password=ufbUwAlquerKuKlKMxDzNGEqRn1KJhOm-wDu7drbl1o